name: Linux Build

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake g++
          sudo apt-get install libglfw3-dev
          if [ ! -d "build" ]; then
            mkdir build
          fi

      - name: show dir
        run: |
          pwd
          ls

      - name: Configure build
        run: |
          cmake --build build --target 2D-Engine -j 6

      - name: Build project
        run: |
          make

#      - name: Run tests
#        run: |
#          cd build
#          ctest --output-on-failure