name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          choco install mingw

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -S /home/runner/work/2D-Engine/2D-Engine ./

      - name: Build project
        run: |
          cd build
          make

#      - name: Run tests
#        run: |
#          cd build
#          ctest --output-on-failure
